### ISSUE TITLE
ERROR: heroku run python manage.py migrate

### ISSUE THREAD

**Issue by yeseong31** [bjo6300/Itrencotech-web-page#109]
2/19 01:21

'git push heroku master'까지 완료한 뒤 heroku에 migrate하기 위해 
'heroku run python manage.py migrate' 명령어를 작성했는데, 다음의 오류가 발생하였음

**ModuleNotFoundError: No module named 'config.my_settings'**
(config/settings.py까지 GitHub에 push해 둔 상태에서 발생)

GitHub에는 my_settings.py 파일이 없기 때문에 발생하는 문제로 보이는데
해당 파일은 SECRET_KEY나 Email 계정에 대한 개인정보가 포함되어 있어 함부로 push할 수 없으므로 다른 대책이 필요해 보임

일단 이만 하고 내일 생각해 보기로... ㅎㅎ

**Comment by bjo6300** [comment]
my_settings.py도 그냥 올려야하나... 다른 프로젝트들 어떻게 했는지 찾아볼게

**Comment by yeseong31** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66625672/155284354-04baf4f3-ea36-41ea-a00b-99edaaafca79.png">

DB 연동 작업만 하면...!

**Comment by yeseong31** [comment]
my_settings.py까지 GitHub에 Push하여 해결 (공개 설정은 Private로)
