### ISSUE TITLE
0223 ValueError: Dependency on app with no migrations: common

### ISSUE THREAD

**Issue by yeseong31** [bjo6300/Itrencotech-web-page#111]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/66625672/155284460-8e35f9d9-6cb4-43c2-bb0d-9dfd41273cc2.png">

DB 작업만 하면 끝난다...!!

**Comment by bjo6300** [comment]
common 제발

**Comment by yeseong31** [comment]
common 제발 ㅡㅡ

**Comment by yeseong31** [comment]
일단 common은 해결^^
